sudo: false
language: node_js
node_js:
  - stable
cache: npm
install:
  - npm install
branches:
  only:
    - blog-source-bak
script:
  - hexo clean
  - hexo g
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    target-branch: master
    on:
      branch: blog-source-bak
    local-dir: public